### ISSUE TITLE
Repository topics

### ISSUE THREAD

**Issue by kevinpapst** [hmr-it/EmptyDescriptionCheckerBundle#1]
Maybe you could/want to change the repo topics?

Compare yours:
<img width="278" alt="Bildschirmfoto 2019-09-10 um 00 07 05" src="https://user-images.githubusercontent.com/533162/64569862-f9a16000-d35e-11e9-8b53-c7210c9da9bc.png">

With these existing topics:
- https://github.com/topics/kimai-plugin
- https://github.com/topics/kimai-bundle

I am not sure if I already linked these topics somewhere, but I will for sure in the future.

**Comment by hmr-it-jr** [comment]
Thanks Kevin! I've updated them.
